#!/bin/bash
set -euo pipefail

# KafClaw Workshop Setup
# Creates a 4-agent group: 1 Electron desktop + 3 headless Docker agents
# sharing one gateway, one KafScale bus with local MinIO for S3 storage.

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
EXAMPLES_DIR="$PROJECT_DIR/examples/workshop"

GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m'

info()  { echo -e "${GREEN}[INFO]${NC} $*"; }
warn()  { echo -e "${YELLOW}[WARN]${NC} $*"; }
error() { echo -e "${RED}[ERROR]${NC} $*"; exit 1; }

# ----- Prerequisites -----

info "Checking prerequisites..."

command -v docker >/dev/null 2>&1 || error "Docker is required. Install: https://docs.docker.com/get-docker/"
command -v git    >/dev/null 2>&1 || error "Git is required."

if ! docker compose version >/dev/null 2>&1; then
    error "Docker Compose v2 is required (docker compose, not docker-compose)."
fi

info "Prerequisites OK."

# ----- Configuration -----

ENV_FILE="$PROJECT_DIR/.env"

if [ -f "$ENV_FILE" ]; then
    info ".env file already exists at $ENV_FILE"
    read -rp "Overwrite it? [y/N] " overwrite
    if [[ ! "$overwrite" =~ ^[Yy]$ ]]; then
        info "Keeping existing .env file."
    else
        rm "$ENV_FILE"
    fi
fi

if [ ! -f "$ENV_FILE" ]; then
    info "Creating .env configuration..."

    # OpenRouter API key
    read -rp "OpenRouter API key (OPENROUTER_API_KEY): " api_key
    if [ -z "$api_key" ]; then
        error "OPENROUTER_API_KEY is required."
    fi

    # Auth token
    auth_token=$(openssl rand -hex 16 2>/dev/null || head -c 32 /dev/urandom | xxd -p | head -c 32)
    info "Generated auth token for headless agents."

    # Group name
    read -rp "Group name [workshop]: " group_name
    group_name="${group_name:-workshop}"

    # KafScale registry
    echo ""
    info "KafScale images are needed for broker, lfs-proxy, and console."
    read -rp "KafScale registry [ghcr.io/kafscale]: " kafscale_registry
    kafscale_registry="${kafscale_registry:-ghcr.io/kafscale}"
    read -rp "KafScale image tag [dev]: " kafscale_tag
    kafscale_tag="${kafscale_tag:-dev}"

    # Work repos — ask for each agent
    echo ""
    info "Each agent can mount a GitHub repo as its work directory."
    info "Leave blank to use a local Docker volume."
    echo ""

    read -rp "Agent 1 (researcher) work repo path or git URL [local volume]: " agent1_repo
    read -rp "Agent 2 (coder) work repo path or git URL [local volume]: " agent2_repo
    read -rp "Agent 3 (reviewer) work repo path or git URL [local volume]: " agent3_repo

    cat > "$ENV_FILE" <<EOF
# KafClaw Workshop — generated by setup-workshop.sh
OPENROUTER_API_KEY=$api_key
AGENT_AUTH_TOKEN=$auth_token
GROUP_NAME=$group_name
KAFSCALE_REGISTRY=$kafscale_registry
KAFSCALE_TAG=$kafscale_tag
EOF

    # Set work repo paths or git URLs
    for i in 1 2 3; do
        var="agent${i}_repo"
        value="${!var}"
        if [ -n "$value" ]; then
            if [[ "$value" == http* || "$value" == git@* ]]; then
                echo "AGENT${i}_WORK_REPO_GIT_URL=$value" >> "$ENV_FILE"
            else
                echo "AGENT${i}_WORK_REPO=$value" >> "$ENV_FILE"
            fi
        fi
    done

    info "Wrote $ENV_FILE"
fi

# ----- Build Docker Image -----

info "Building KafClaw Docker image..."
cd "$PROJECT_DIR"
docker build -t kafclaw:local -f Dockerfile .
info "Docker image kafclaw:local built."

# ----- Workspace Templates -----

info "Workshop workspace templates are at:"
echo "  $EXAMPLES_DIR/agent-researcher/workspace/SOUL.md"
echo "  $EXAMPLES_DIR/agent-coder/workspace/SOUL.md"
echo "  $EXAMPLES_DIR/agent-reviewer/workspace/SOUL.md"
echo ""
info "Customize these SOUL.md files to shape each agent's personality."

# ----- Start Infrastructure -----

read -rp "Start the workshop now? [Y/n] " start_now
if [[ "$start_now" =~ ^[Nn]$ ]]; then
    info "Skipping startup. Run later with: make workshop-up"
else
    info "Starting KafScale platform + agents..."
    docker compose -f docker-compose.group.yml up -d
    info "Workshop started!"
    echo ""
    echo "  MinIO S3:          http://localhost:9000  (console: http://localhost:9001)"
    echo "  etcd:              http://localhost:2379"
    echo "  KafScale broker:   localhost:9092"
    echo "  KafScale LFS:      http://localhost:8080"
    echo "  KafScale console:  http://localhost:3080  (kafscaleadmin/kafscale)"
    echo "  Agents:            agent-researcher, agent-coder, agent-reviewer"
    echo ""
    echo "  View logs:   make workshop-logs"
    echo "  Stop:        make workshop-down"
fi

# ----- Electron App Instructions -----

echo ""
info "=== Desktop Agent (Electron) Setup ==="
echo ""
echo "  To connect your Mac as the 4th agent (orchestrator):"
echo ""
echo "  1. Add to ~/.gomikrobot/config.json:"
echo '     {'
echo '       "group": {'
echo '         "enabled": true,'
echo "         \"groupName\": \"$(grep GROUP_NAME "$ENV_FILE" 2>/dev/null | cut -d= -f2 || echo workshop)\","
echo '         "agentId": "desktop-orchestrator",'
echo '         "kafkaBrokers": "localhost:9092",'
echo '         "lfsProxyUrl": "http://localhost:8080"'
echo '       },'
echo '       "orchestrator": {'
echo '         "enabled": true,'
echo '         "role": "orchestrator"'
echo '       }'
echo '     }'
echo ""
echo "  2. Start the gateway:"
echo "     make run-full"
echo ""
echo "  Or start Electron:"
echo "     make electron-start-full"
echo ""
info "Setup complete."
